apiVersion: v1
kind: Secret
metadata:
  name: server-secret
stringData:
  spoonacular-api-key: ""
  mongodb-uri: ""
  jwt-secret: ""
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  labels:
    app: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  labels:
    app: ingress-nginx
 
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  labels:
    app: ingress-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  labels:
    app: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ingress-role
  labels:
    app: ingress-nginx
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - pods
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - ingress-controller-leader-nginx
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress-role-binding
  labels:
    app: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-role
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fastapi-server
        image: tastebuddiesbackend.azurecr.io/tastebuddiesbackend
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8000
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        env: 
          - name: FOODAPIKEY
            valueFrom: 
              secretKeyRef: 
                key: spoonacular-api-key
                name: server-secret
          - name: MONGOURI
            valueFrom: 
              secretKeyRef: 
                key: mongodb-uri
                name: server-secret
          - name: JWTSECRET
            valueFrom: 
              secretKeyRef: 
                key: jwt-secret
                name: server-secret
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
  labels:
    app: fastapi-server
spec:
  type: 'LoadBalancer'
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: fastapi-server


